[package]
name = "mini_utils"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.72"
log = {version = "0.4.8", features = ["std"]}