language: rust
dist: trusty
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mysql-connector-c ; fi

script:
  - cargo test
